# Generated by Django 5.2.8 on 2025-11-28 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actividad',
            name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='actividad',
            name='nombre',
        ),
        migrations.AddField(
            model_name='actividad',
            name='completada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='actividad',
            name='fecha',
            field=models.DateField(default='2025-11-27'),
        ),
        migrations.AddField(
            model_name='actividad',
            name='titulo',
            field=models.CharField(default='Titulo por defecto', max_length=200),
            preserve_default=False,
        ),
    ]
